services:
  - type: web
    name: noble-farm-erp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run setup && npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE
        scope: run
        sync: false
      - key: JWT_SECRET
        scope: run
        sync: false
      - key: NODE_ENV
        value: production
      - key: PUBLIC_SERVER_FILE
        value: https://noble-farm-erp-backend.onrender.com
      - key: PORT
        value: '10000'
      - key: OPENSSL_CONF
        value: /dev/null
